export { applySpecifierPatternMatching } from "./src/applySpecifierPatternMatching.js"
export { metaMapToSpecifierMetaMap } from "./src/metaMapToSpecifierMetaMap.js"
export { normalizeSpecifierMetaMap } from "./src/normalizeSpecifierMetaMap.js"
export { urlCanContainsMetaMatching } from "./src/urlCanContainsMetaMatching.js"
export { urlToMeta } from "./src/urlToMeta.js"
